"""
Shared pytest fixtures for the FitForge test suite.

Retrieval fixtures (sample_chunks, mock_embed_model, mock_reranker) are used
by the existing unit tests in test_retrieval.py / test_generation.py / test_agent.py.

API integration fixtures (db, client, mock_groq) are used by test_api.py and
require a real PostgreSQL database at DATABASE_URL.
"""

import json
import os

import numpy as np
import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.database import Base, get_db
from app.main import app
from app.services.retrieval_service import ChunkResult

DATABASE_URL = os.environ.get("DATABASE_URL")

# ── Fake Groq objects used by the mock_groq fixture ───────────────────────────

_MINIMAL_PLAN = {
    "title": "CI Test Plan",
    "summary": "Generated by the CI test suite.",
    "generated_for": "Tester",
    "general_tips": ["Stay consistent"],
    "citations": [],
    "grounded": True,
    "days": [
        {
            "day": "Day 1",
            "focus": "Full Body",
            "duration_minutes": 45,
            "exercises": [
                {
                    "name": "Squat",
                    "sets": 3,
                    "reps": "8-10",
                    "rest_seconds": 90,
                    "notes": "Keep chest up",
                }
            ],
        }
    ],
}


class _FakeMsg:
    content = json.dumps(_MINIMAL_PLAN)


class _FakeChoice:
    message = _FakeMsg()


class _FakeCompletion:
    choices = [_FakeChoice()]
    usage = None


class _FakeCompletions:
    def create(self, **kwargs):
        return _FakeCompletion()


class _FakeChat:
    completions = _FakeCompletions()


class _FakeGroqClient:
    chat = _FakeChat()


# ---------------------------------------------------------------------------
# Sample ChunkResult fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def sample_chunks():
    return [
        ChunkResult(
            chunk_id=1,
            raw_content="Progressive overload is the key principle for strength gains.",
            contextualized_content="Context blurb A. Progressive overload is the key principle.",
            metadata={"topic": "progressive_overload", "fitness_goals": [], "fitness_levels": []},
            score=0.9,
        ),
        ChunkResult(
            chunk_id=2,
            raw_content="ACSM recommends 3-5 sets per muscle group per week for beginners.",
            contextualized_content="Context blurb B. ACSM recommends 3-5 sets for beginners.",
            metadata={"topic": "resistance_training", "fitness_goals": ["build_muscle"], "fitness_levels": ["beginner"]},
            score=0.8,
        ),
        ChunkResult(
            chunk_id=3,
            raw_content="Rest 2-5 minutes between heavy compound sets.",
            contextualized_content="Context blurb C. Rest 2-5 minutes between heavy sets.",
            metadata={"topic": "resistance_training", "fitness_goals": [], "fitness_levels": []},
            score=0.7,
        ),
        ChunkResult(
            chunk_id=4,
            raw_content="Protein intake should be 1.6-2.2g per kg bodyweight.",
            contextualized_content="Context blurb D. Protein 1.6-2.2g/kg for muscle building.",
            metadata={"topic": "nutrition", "fitness_goals": ["build_muscle"], "fitness_levels": []},
            score=0.6,
        ),
        ChunkResult(
            chunk_id=5,
            raw_content="Deload weeks reduce volume by 40-50% to dissipate fatigue.",
            contextualized_content="Context blurb E. Deload weeks reduce volume to aid recovery.",
            metadata={"topic": "progressive_overload", "fitness_goals": [], "fitness_levels": []},
            score=0.5,
        ),
    ]


@pytest.fixture
def mock_embed_model(monkeypatch):
    """Patch _get_embed_model to return a mock that yields zero vectors."""
    import app.services.retrieval_service as svc

    class FakeEmbedder:
        def encode(self, text, normalize_embeddings=False):
            return np.zeros(384, dtype=np.float32)

    fake = FakeEmbedder()
    monkeypatch.setattr(svc, "_embed_model", fake)
    return fake


@pytest.fixture
def mock_reranker(monkeypatch):
    """Patch _get_reranker to return a mock that scores by reverse-insertion-order."""
    import app.services.retrieval_service as svc

    class FakeReranker:
        def predict(self, pairs):
            # Return descending scores so first pair gets the highest score
            return np.array([10.0 - i for i in range(len(pairs))], dtype=np.float32)

    fake = FakeReranker()
    monkeypatch.setattr(svc, "_reranker", fake)
    return fake


# ---------------------------------------------------------------------------
# API integration fixtures (require DATABASE_URL → real PostgreSQL)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def _api_engine():
    """Session-scoped SQLAlchemy engine for integration tests.

    Skips the entire fixture (and all tests that depend on it) when
    DATABASE_URL is not set, so unit-test-only runs are unaffected.
    """
    if not DATABASE_URL:
        pytest.skip("DATABASE_URL not set — skipping API integration tests")
    engine = create_engine(DATABASE_URL)
    # Idempotent: alembic upgrade head already ran in CI; this is a no-op there.
    Base.metadata.create_all(bind=engine)
    yield engine
    engine.dispose()


@pytest.fixture
def db(_api_engine):
    """Function-scoped DB session. Each test gets a fresh session; data
    written by routes is visible because routes commit to the same DB."""
    Session = sessionmaker(bind=_api_engine)
    session = Session()
    yield session
    session.close()


@pytest.fixture
def client(db):
    """Function-scoped TestClient with get_db overridden to the test session."""
    def _override():
        yield db

    app.dependency_overrides[get_db] = _override
    with TestClient(app) as c:
        yield c
    app.dependency_overrides.clear()


@pytest.fixture
def mock_groq(monkeypatch):
    """Patch the Groq client and retrieval pipeline so /generate needs no
    live API key and no ML model weights."""
    from app.services.retrieval_service import RetrievalResult

    monkeypatch.setattr("app.services.ai_service._client", _FakeGroqClient())
    monkeypatch.setattr(
        "app.services.retrieval_service.retrieve",
        lambda *a, **kw: RetrievalResult(
            chunks=[], scores=[], low_confidence=True, retrieval_mode="hybrid"
        ),
    )
