"""add_kb_chunks

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-07-21 00:00:00.000000

This migration enables the pgvector extension and creates the kb_chunks table
used by the RAG pipeline. The table is hand-written (not autogenerated) because:
  1. vector(384) is not a native SQLAlchemy column type.
  2. The search_vector TSVECTOR column uses GENERATED ALWAYS AS ... STORED,
     which Alembic autogenerate cannot model.
The alembic/env.py include_object hook excludes kb_chunks from future
autogenerate runs to prevent broken DDL being emitted.
"""

from alembic import op


revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1: Enable pgvector (idempotent)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Step 2: Create the table
    op.execute("""
        CREATE TABLE kb_chunks (
            id                     SERIAL PRIMARY KEY,
            content_hash           VARCHAR(64)   NOT NULL UNIQUE,
            raw_content            TEXT          NOT NULL,
            contextualized_content TEXT          NOT NULL,
            metadata               JSONB         NOT NULL DEFAULT '{}',
            embedding              vector(384)   NOT NULL,
            raw_embedding          vector(384)   NOT NULL,
            search_vector          TSVECTOR GENERATED ALWAYS AS (
                                       to_tsvector('english', contextualized_content)
                                   ) STORED,
            created_at             TIMESTAMPTZ   NOT NULL DEFAULT now()
        )
    """)

    # Step 3: HNSW index for approximate cosine nearest-neighbour on contextualized embeddings
    # HNSW (pgvector >= 0.5) works correctly at small corpus sizes unlike IVFFlat,
    # which requires lists ≈ sqrt(row_count) calibration and is ineffective below ~500 rows.
    op.execute("""
        CREATE INDEX ix_kb_chunks_embedding
            ON kb_chunks USING hnsw (embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64)
    """)

    # Step 4: HNSW index on raw embeddings — used by the contextual-vs-raw ablation study
    op.execute("""
        CREATE INDEX ix_kb_chunks_raw_embedding
            ON kb_chunks USING hnsw (raw_embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64)
    """)

    # Step 5: GIN index on the generated tsvector for full-text search
    op.execute("""
        CREATE INDEX ix_kb_chunks_search_vector
            ON kb_chunks USING gin(search_vector)
    """)

    # Step 6: GIN index on metadata JSONB for goal/level/equipment filtering
    op.execute("""
        CREATE INDEX ix_kb_chunks_metadata
            ON kb_chunks USING gin(metadata jsonb_path_ops)
    """)

    # Step 7: B-tree index on content_hash for O(log n) idempotency lookups
    op.execute("""
        CREATE INDEX ix_kb_chunks_content_hash
            ON kb_chunks (content_hash)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS kb_chunks")
    # Do NOT drop the vector extension — other future tables may use it.
    # If you need to remove the extension entirely, do so manually.
