import { Lightbulb, Sparkles } from 'lucide-react'
import DayCard from './DayCard'

/**
 * Renders the complete workout plan generated by Claude AI.
 *
 * Layout:
 *   1. Plan title + personalised greeting
 *   2. Summary paragraph
 *   3. Collapsible DayCard per training day (first day open by default)
 *   4. General tips section
 *
 * @param {Object}   plan      - WorkoutPlan object from the API
 * @param {Function} onLogDay  - Optional; passed down to each DayCard for logging
 */
export default function WorkoutPlan({ plan, onLogDay }) {
  return (
    <div className="animate-fade-in">
      {/* ── Header ── */}
      <div className="mb-8">
        <div className="flex items-center gap-2 text-brand-400 text-sm font-medium mb-3">
          <Sparkles className="w-4 h-4" />
          Generated for {plan.generated_for}
        </div>

        <h1 className="text-3xl font-extrabold text-white leading-tight mb-4">
          {plan.title}
        </h1>

        <p className="text-gray-400 leading-relaxed">{plan.summary}</p>
      </div>

      {/* ── Day cards ── */}
      <section className="space-y-3 mb-10">
        <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
          Weekly Schedule
        </h2>
        {plan.days.map((day, index) => (
          <DayCard
            key={index}
            day={day}
            index={index}
            defaultOpen={index === 0}  // First day starts expanded
            onLogDay={onLogDay}
          />
        ))}
      </section>

      {/* ── General tips ── */}
      {plan.general_tips?.length > 0 && (
        <section className="card p-6">
          <div className="flex items-center gap-2 text-yellow-400 mb-4">
            <Lightbulb className="w-5 h-5" />
            <h2 className="font-semibold">General Tips</h2>
          </div>
          <ul className="space-y-3">
            {plan.general_tips.map((tip, i) => (
              <li key={i} className="flex items-start gap-3 text-sm text-gray-300">
                <span className="w-5 h-5 rounded-full bg-yellow-500/10 text-yellow-400 text-xs font-bold flex items-center justify-center flex-shrink-0 mt-0.5">
                  {i + 1}
                </span>
                {tip}
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  )
}
